# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_nb": "00_core.ipynb",
         "notebook2do": "00_core.ipynb",
         "simple_doexport": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hugetim.github.io/simple_doexport/"

git_url = "https://github.com/hugetim/simple_doexport/tree/master/"

def custom_doc_links(name): return None
